"use client";
import {useState,type FormEvent} from "react";
import "../login/login.css";

export default function ParentSignupPage(){
 const [name,setName]=useState(""),[phone,setPhone]=useState(""),[pw,setPw]=useState(""),[pw2,setPw2]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const [completed,setCompleted]=useState<{message:string;linkedNames:string[]} | null>(null);
 // SOS323: 개인정보 보호법 제15조·제22조에 따라 수집·이용 동의를 별도로 받아야 합니다.
 // 약관 동의와 개인정보 동의는 묶어서 받을 수 없고, 항목별로 구분해 표시해야 합니다.
 const [agreeTerms,setAgreeTerms]=useState(false);
 const [agreePrivacy,setAgreePrivacy]=useState(false);
 const [agreeOverseas,setAgreeOverseas]=useState(false);
 const allAgreed=agreeTerms&&agreePrivacy&&agreeOverseas;
 const submit=async(e:FormEvent)=>{e.preventDefault();setError("");if(pw!==pw2)return setError("비밀번호가 서로 다릅니다.");if(!allAgreed)return setError("필수 항목에 모두 동의해 주세요.");setBusy(true);try{const r=await fetch("/api/parent/signup",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,phone,password:pw,consent:{terms:agreeTerms,privacy:agreePrivacy,overseas:agreeOverseas,agreedAt:new Date().toISOString()}})});const j=await r.json();if(!r.ok)throw new Error(j.message);setCompleted({message:j.message||"학부모 계정이 만들어졌습니다.",linkedNames:Array.isArray(j.linkedNames)?j.linkedNames:[]});}catch(e){setError(e instanceof Error?e.message:"가입하지 못했습니다.");}finally{setBusy(false)}};
 if(completed)return <main className="mp-login-page"><header className="mp-login-header"><div><img src="/mathpooh-logo.png" alt=""/><strong>MATHPOOH</strong></div></header><section className="mp-login-wrap"><div className="mp-login-card signup-complete"><div className="complete-mark">✓</div><div className="mp-login-heading"><h2>학부모 가입 완료</h2><p>{completed.message}</p></div><div className="service-account-notice"><b>SOS 전용 계정입니다</b><span>방금 만든 계정은 <strong>sos.mathpooh.com</strong>에서만 사용합니다. 기존 <strong>mathpooh.com</strong> 계정과는 연결되지 않는 별도 계정입니다.</span></div><div className="next-steps"><b>이제 이렇게 진행하세요</b><ol><li><strong>학부모 로그인</strong><span>방금 가입한 학부모 휴대폰번호와 비밀번호를 사용합니다.</span></li><li><strong>자녀 연결 또는 계정 생성</strong><span>학생 계정은 학부모 계정과 별도이며 비밀번호도 따로 설정합니다.</span></li><li><strong>SOS 회차 신청</strong><span>자녀를 선택하고 필요한 회차를 신청합니다.</span></li><li><strong>결제 확인 후 이용</strong><span>관리자 확인이 끝나면 해당 회차가 자동 등록됩니다.</span></li></ol></div><div className="account-warning"><b>중요</b><span>학부모 비밀번호와 학생 비밀번호는 서로 공유되지 않습니다. 학생에게는 학생용 로그인 정보만 알려주세요.</span></div><a className="mp-login-submit complete-login" href="/parent-login">학부모 로그인하기 →</a></div></section><style>{`.signup-complete{text-align:left}.complete-mark{width:54px;height:54px;margin:0 auto 12px;border-radius:50%;display:grid;place-items:center;background:#2f6937;color:#fff;font-size:28px;font-weight:900}.signup-complete .mp-login-heading{text-align:center}.service-account-notice{display:grid;gap:4px;padding:13px 14px;background:#eef5ff;border:1px solid #cdddf2;border-radius:10px;line-height:1.55}.service-account-notice b{font-size:13px;color:#285384}.service-account-notice span{font-size:12px;color:#566d87}.next-steps{padding:16px;background:#f5f9f6;border:1px solid #dbe8df;border-radius:12px}.next-steps>b{color:#285c31}.next-steps ol{margin:12px 0 0;padding-left:22px;display:grid;gap:11px}.next-steps li{padding-left:4px;color:#2f6937}.next-steps li strong,.next-steps li span{display:block}.next-steps li strong{font-size:13px;color:#304438}.next-steps li span{margin-top:2px;font-size:12px;line-height:1.5;color:#758078}.account-warning{display:flex;gap:9px;padding:12px 14px;background:#fff7e9;border:1px solid #efd5a8;border-radius:10px;font-size:12px;line-height:1.55;color:#79501d}.account-warning b{flex:none}.complete-login{display:grid;place-items:center;text-decoration:none;margin-top:2px}`}</style></main>;
 return <main className="mp-login-page"><header className="mp-login-header"><div><img src="/mathpooh-logo.png" alt=""/><strong>MATHPOOH</strong></div></header><section className="mp-login-wrap"><form onSubmit={submit} className="mp-login-card"><img className="mp-card-logo" src="/mathpooh-logo.png" alt="MATHPOOH"/><div className="mp-login-heading"><h2>학부모 신규가입</h2><p>학부모 계정을 만든 뒤 자녀를 연결하고 원하는 SOS 회차를 신청합니다.</p></div><div className="site-account-notice"><b>sos.mathpooh.com 전용 가입</b><span>기존 <strong>mathpooh.com</strong> 계정과는 관련없는 별도 계정입니다. SOS를 처음 이용하시면 이곳에서 새로 가입해 주세요.</span></div><div className="signup-flow"><span><b>1</b>학부모 가입</span><i>→</i><span><b>2</b>자녀 연결</span><i>→</i><span><b>3</b>회차 신청</span></div><div className="separate-account"><b>학부모 계정과 학생 계정도 별도입니다.</b><span>지금 입력하는 비밀번호는 학부모 로그인에만 사용합니다. 학생 비밀번호는 자녀 계정을 만들 때 따로 정합니다.</span></div><label className="mp-login-field"><span>학부모 성함</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="성함" autoFocus/></label><label className="mp-login-field"><span>학부모 휴대폰번호</span><input type="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="01012345678"/></label><label className="mp-login-field"><span>학부모 비밀번호</span><input type="password" value={pw} onChange={e=>setPw(e.target.value)} placeholder="학부모가 사용할 비밀번호 · 6자리 이상"/></label><label className="mp-login-field"><span>학부모 비밀번호 확인</span><input type="password" value={pw2} onChange={e=>setPw2(e.target.value)} placeholder="한 번 더 입력"/></label><div className="mp-consent">
  <label><input type="checkbox" checked={agreeTerms} onChange={e=>setAgreeTerms(e.target.checked)}/><span>[필수] <a href="/terms" target="_blank" rel="noreferrer">이용약관</a>에 동의합니다.</span></label>
  <label><input type="checkbox" checked={agreePrivacy} onChange={e=>setAgreePrivacy(e.target.checked)}/><span>[필수] <a href="/privacy" target="_blank" rel="noreferrer">개인정보 수집·이용</a>에 동의합니다.</span></label>
  <p className="mp-consent-detail">수집 항목 : 학부모 성명·휴대전화번호, 자녀 성명·휴대전화번호·학교·학년, 학습 기록<br/>이용 목적 : 학습 진단·처방 제공 및 학원 수업 운영<br/>보유 기간 : 수강 종료 후 1년 (학습 기록 3년)</p>
  <label><input type="checkbox" checked={agreeOverseas} onChange={e=>setAgreeOverseas(e.target.checked)}/><span>[필수] 개인정보의 <a href="/privacy" target="_blank" rel="noreferrer">국외 이전</a>에 동의합니다.</span></label>
  <p className="mp-consent-detail">AI 학습 분석을 위해 답안·풀이사진이 미국(OpenAI)으로 전송됩니다. 동의를 거부할 수 있으나 서비스 이용이 제한됩니다.</p>
  <label className="all"><input type="checkbox" checked={allAgreed} onChange={e=>{const v=e.target.checked;setAgreeTerms(v);setAgreePrivacy(v);setAgreeOverseas(v);}}/><span><b>위 필수 항목에 모두 동의합니다.</b></span></label>
</div>
{error?<div className="mp-login-error">{error}</div>:null}<button type="submit" disabled={busy||!allAgreed} className="mp-login-submit">{busy?"가입 처리 중":"학부모 계정 만들기 →"}</button><p className="mp-login-help">가입 후 학부모 페이지에서 기존 자녀 연결 또는 새 자녀 계정 만들기를 할 수 있습니다.</p><a className="mp-admin-login-link back" href="/parent-login">← 학부모 로그인</a></form><p className="mp-login-copyright">© 2026 MATHPOOH</p>
 <style>{`
  .mp-consent{display:flex;flex-direction:column;gap:7px;margin:4px 0 2px;padding:14px;background:#f7faf8;border:1px solid #dde7e1;border-radius:11px}
  .mp-consent label{display:flex;align-items:flex-start;gap:8px;font-size:13px;color:#3d4a43;line-height:1.55;cursor:pointer}
  .mp-consent input{margin-top:2px;width:16px;height:16px;flex:none;accent-color:#2f6937}
  .mp-consent a{color:#2f6937;font-weight:800}
  .mp-consent-detail{margin:-2px 0 6px 24px;font-size:11.5px;color:#7b877f;line-height:1.65}
  .mp-consent .all{margin-top:6px;padding-top:9px;border-top:1px solid #e2ebe5}
  .signup-flow{display:flex;align-items:center;justify-content:center;gap:7px;padding:10px 8px;background:#f5f9f6;border-radius:10px;color:#526158;font-size:11.5px;font-weight:800}
  .signup-flow span{display:flex;align-items:center;gap:4px}.signup-flow b{width:20px;height:20px;display:grid;place-items:center;border-radius:50%;background:#2f6937;color:#fff;font-size:11px}.signup-flow i{color:#a5afa8;font-style:normal}
  .separate-account{display:grid;gap:4px;padding:12px 14px;background:#fff7e9;border:1px solid #efd5a8;border-radius:10px;line-height:1.5}.separate-account b{font-size:13px;color:#704715}.separate-account span{font-size:12px;color:#846643}
  .site-account-notice{display:grid;gap:4px;padding:12px 14px;background:#eef5ff;border:1px solid #cdddf2;border-radius:10px;line-height:1.5}.site-account-notice b{font-size:13px;color:#285384}.site-account-notice span{font-size:12px;color:#566d87}
 `}</style></section></main>;
}
