"use client";
import {useState,type FormEvent} from "react";
import "../login/login.css";

export default function ParentSignupPage(){
 const [name,setName]=useState(""),[phone,setPhone]=useState(""),[pw,setPw]=useState(""),[pw2,setPw2]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(false);
 const submit=async(e:FormEvent)=>{e.preventDefault();setError("");if(pw!==pw2)return setError("비밀번호가 서로 다릅니다.");setBusy(true);try{const r=await fetch("/api/parent/signup",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({name,phone,password:pw})});const j=await r.json();if(!r.ok)throw new Error(j.message);location.href="/parent-login?joined=1";}catch(e){setError(e instanceof Error?e.message:"가입하지 못했습니다.");}finally{setBusy(false)}};
 return <main className="mp-login-page"><header className="mp-login-header"><div><img src="/mathpooh-logo.png" alt=""/><strong>MATHPOOH</strong></div></header><section className="mp-login-wrap"><form onSubmit={submit} className="mp-login-card"><img className="mp-card-logo" src="/mathpooh-logo.png" alt="MATHPOOH"/><div className="mp-login-heading"><h2>학부모 신규가입</h2><p>학부모 계정을 먼저 만든 뒤 자녀를 등록하고 SOS를 신청합니다.</p></div><label className="mp-login-field"><span>학부모 성함</span><input value={name} onChange={e=>setName(e.target.value)} placeholder="성함" autoFocus/></label><label className="mp-login-field"><span>학부모 휴대폰번호</span><input type="tel" value={phone} onChange={e=>setPhone(e.target.value)} placeholder="01012345678"/></label><label className="mp-login-field"><span>비밀번호</span><input type="password" value={pw} onChange={e=>setPw(e.target.value)} placeholder="6자리 이상"/></label><label className="mp-login-field"><span>비밀번호 확인</span><input type="password" value={pw2} onChange={e=>setPw2(e.target.value)} placeholder="한 번 더 입력"/></label>{error?<div className="mp-login-error">{error}</div>:null}<button type="submit" disabled={busy} className="mp-login-submit">{busy?"가입 처리 중":"학부모 계정 만들기 →"}</button><p className="mp-login-help">가입 후 학부모 페이지에서 기존 자녀 연결 또는 새 자녀 계정 만들기를 할 수 있습니다.</p><a className="mp-admin-login-link back" href="/parent-login">← 학부모 로그인</a></form><p className="mp-login-copyright">© 2026 MATHPOOH</p></section></main>;
}
