"use client";
import {useEffect,useState} from "react";
import AdminPortalShell from "@/components/admin-portal-sidebar";
export default function ProblemErrors(){
 const [items,setItems]=useState<any[]>([]),[error,setError]=useState(""),[loading,setLoading]=useState(true),[busy,setBusy]=useState(false),[keyword,setKeyword]=useState("");
 const [imageUrl,setImageUrl]=useState("");
 const [editing,setEditing]=useState<any>(null),[notice,setNotice]=useState("");
 async function load(){try{const r=await fetch("/api/admin/problem-errors",{cache:"no-store"});const d=await r.json();if(!r.ok)throw Error(d.message);setItems(d.items??[]);}catch(e){setError(String((e as Error).message));}finally{setLoading(false);}}
 useEffect(()=>{void load();},[]);
 useEffect(()=>{let cancelled=false;setImageUrl("");if(editing?.kind==="bank")void fetch(`/api/problem-bank/questions/${editing.id}/image`).then(r=>r.json()).then(d=>{if(!cancelled)setImageUrl(d.imageUrl??"");}).catch(()=>{});return()=>{cancelled=true;};},[editing?.id,editing?.kind]);
 async function act(p:any,action:string){
  if(action==="restore"&&!confirm("문제·정답·해설을 검수했습니까? 오류 보관을 해제하고 이전 사용 상태로 복원합니다."))return;
  setBusy(true);setError("");setNotice("");
  try{const r=await fetch("/api/admin/problem-errors",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({...p,action,reviewed:action==="restore"})});const d=await r.json();if(!r.ok)throw Error(d.message);setEditing(null);setNotice(action==="restore"?"검수 완료 후 복원했습니다.":"수정 내용을 저장했습니다. 검수 후 복원해 주세요.");await load();}catch(e){setError((e as Error).message);}finally{setBusy(false);}
 }
 const filtered=items.filter(p=>`${p.title??p.question_text} ${p.subject} ${p.review?.reason}`.includes(keyword));
 return <AdminPortalShell current="problem-errors"><main className="errors-page"><header><small>MATHPOOH SOS</small><h1>오류문항 보관함</h1><p>새 학습 배정에서 제외된 문항입니다. 수정 내용을 저장한 뒤 검수하고 복원하세요.</p><p>이미 배정된 학습과 학생의 답안·점수는 유지됩니다.</p></header><nav><a href="/problem-bank">SOS 문제은행</a><a href="/admin/ai-generated-bank">AI 생성 문제은행</a><button onClick={()=>void load()}>새로고침</button></nav><div className="search"><b>검수 대기 {items.length}문항</b><input placeholder="문항·과목·오류 사유 검색" value={keyword} onChange={e=>setKeyword(e.target.value)}/></div>{error&&<p role="alert" className="error">{error}</p>}{notice&&<p role="status">{notice}</p>}{loading?<p>불러오는 중…</p>:!filtered.length?<section>오류로 분리된 문항이 없습니다.</section>:filtered.map(p=><section key={p.kind+p.id}><small>{p.kind==="ai"?"AI 생성문항":"SOS 문제은행"} · {p.subject}</small><h2>{p.title||p.question_text}</h2><p className="reason">오류 사유: {p.review?.reason}</p><p>등록 {new Date(p.review.reportedAt).toLocaleString("ko-KR")}</p><div className="actions"><button disabled={busy} onClick={()=>setEditing({...p,question:p.display_latex||p.question_text})}>문항 확인·수정</button>{p.source_file_id&&<a href={`/admin?menu=problem-sources&source=${encodeURIComponent(p.source_file_id)}`}>원본·이미지 수정</a>}<button disabled={busy} onClick={()=>void act(p,"restore")}>검수 완료·복원</button></div></section>)}{editing&&<div className="backdrop"><form onSubmit={e=>{e.preventDefault();void act(editing,"save");}}><h2>오류문항 수정</h2>{imageUrl&&<img src={imageUrl} alt="오류 보관 문항 원본" style={{maxWidth:"100%"}}/>}{editing.kind==="bank"&&!imageUrl&&<p>원본·이미지 수정에서 문항과 공식 해설을 확인할 수 있습니다.</p>}{editing.kind==="ai"&&<label>문제·수식<textarea required rows={7} value={editing.question} onChange={e=>setEditing({...editing,question:e.target.value})}/></label>}<label>정답<input required value={editing.answer} onChange={e=>setEditing({...editing,answer:e.target.value})}/></label><label>{editing.kind==="ai"?"해설":"문항 요약"}<textarea rows={6} value={editing.kind==="ai"?editing.solution:editing.summary} onChange={e=>setEditing({...editing,[editing.kind==="ai"?"solution":"summary"]:e.target.value})}/></label><p>저장 후에도 오류 보관 상태가 유지됩니다.</p><div className="actions"><button type="button" disabled={busy} onClick={()=>setEditing(null)}>닫기</button><button disabled={busy}>수정 저장</button></div></form></div>}<style jsx>{`
.errors-page{max-width:1200px;margin:auto;padding:36px;color:#213a2b}h1{font-size:30px;margin:10px 0}header p{color:#68786f}nav,.actions,.search{display:flex;gap:12px;align-items:center;flex-wrap:wrap}nav{margin:24px 0}a,button{border:1px solid #ccd9cf;border-radius:9px;padding:10px 15px;background:white;color:#24583a;text-decoration:none;cursor:pointer;font-weight:700}button:disabled{opacity:.5}.search{justify-content:space-between;margin-bottom:20px}input,textarea{padding:12px;border:1px solid #ccd9cf;border-radius:8px;font:inherit;box-sizing:border-box}section{background:white;border:1px solid #dfe7e1;border-radius:16px;padding:24px;margin-bottom:14px}h2{font-size:18px;white-space:pre-wrap;line-height:1.6}.reason,.error{background:#fff2ef;color:#963e31;padding:12px;border-radius:8px}.backdrop{position:fixed;inset:0;background:#14231a77;z-index:1000;display:grid;place-items:center;padding:20px}.backdrop form{background:white;padding:28px;border-radius:16px;width:min(700px,100%);max-height:90vh;overflow:auto}label{display:grid;gap:7px;margin:14px 0}.actions{justify-content:flex-end}@media(max-width:600px){.errors-page{padding:18px}}
`}</style></main></AdminPortalShell>;
}
