"use client";
import {useEffect,useRef,useState} from "react";
export default function ScheduleStart({onSlotChange}:{onSlotChange?:(slot:any)=>void}){
 const [cycles,setCycles]=useState<any[]>([]),[id,setId]=useState(""),[slot,setSlot]=useState<any>(null),[busy,setBusy]=useState(false),[message,setMessage]=useState("");
 const callback=useRef(onSlotChange);callback.current=onSlotChange;
 const selected=useRef(id);selected.current=id;
 useEffect(()=>{let active=true;fetch("/api/admin/learning-cycles",{cache:"no-store"}).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.message||"회차 조회 실패");if(!active)return;const rows=j.cycles??[];setCycles(rows);const today=new Intl.DateTimeFormat("sv-SE",{timeZone:"Asia/Seoul"}).format(new Date());const nearest=[...rows].sort((a,b)=>String(a.start_date).localeCompare(String(b.start_date))).find(c=>String(c.start_date)>=today);setId(nearest?.id??rows[0]?.id??"");}).catch(e=>{if(active)setMessage(e.message);});return()=>{active=false;};},[]);
 useEffect(()=>{let active=true,running=false;setSlot(null);callback.current?.(null);if(!id)return;async function load(){if(running)return;running=true;try{const r=await fetch(`/api/admin/exam-slots?cycleId=${encodeURIComponent(id)}`,{cache:"no-store"});const j=await r.json();if(!r.ok)throw Error(j.message||"배정 조회 실패");if(active){setSlot(j);callback.current?.(j);}}catch(e){if(active)setMessage(e instanceof Error?e.message:"조회 실패");}finally{running=false;}}void load();const t=setInterval(()=>void load(),10000);return()=>{active=false;clearInterval(t);};},[id]);
 const rows=slot?.rows??[],assigned=rows.filter((r:any)=>r.exam_id&&r.booking_status!=="COMPLETED"),started=rows.some((r:any)=>r.booking_status==="IN_PROGRESS"),paused=rows.some((r:any)=>r.booking_status==="IN_PROGRESS"&&r.exam?.paused_at);
 const eligible=assigned.filter((r:any)=>r.sos_gate_open),prepared=eligible.length>0&&eligible.every((r:any)=>r.timer_prepared);
 async function act(action:string){const requested=id;if(action==="start"&&!confirm(`${slot?.cycle?.name} · 응시 가능 ${eligible.length}명을 지금 시작할까요?\n각자 배정된 시험지로 동시에 시작합니다.`))return;setBusy(true);setMessage("");try{const r=await fetch("/api/admin/exam-slots",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,cycleId:requested})});const j=await r.json();if(!r.ok)throw Error(j.message||"처리 실패");if(selected.current!==requested)return;setMessage(action==="prepare"?"회차 타이머 준비 완료 · 시작 버튼을 눌러야 시험이 시작됩니다.":action==="start"?`${j.started}명 시험 시작${j.blocked?.length?` · SOS 미완료 ${j.blocked.length}명 제외`:""}`:action==="pause"?"회차 전체 일시정지":"회차 전체 재개");const next=await fetch(`/api/admin/exam-slots?cycleId=${encodeURIComponent(requested)}`,{cache:"no-store"});const data=await next.json();if(!next.ok)throw Error(data.message);if(selected.current===requested){setSlot(data);callback.current?.(data);}}catch(e){setMessage(e instanceof Error?e.message:"처리 실패");}finally{setBusy(false);}}
 return <section className="cycle-start"><header><div><small>SOS 시험 운영</small><h2>회차별 시험 진행</h2><p>회차를 한 번 시작하면 학생마다 배정된 A/B/C 시험지와 개인 순번으로 응시합니다.</p></div></header><label>진행할 운영 회차<select disabled={busy} aria-label="진행할 운영 회차" value={id} onChange={e=>{setId(e.target.value);setMessage("");}}><option value="">회차 선택</option>{cycles.map(c=><option key={c.id} value={c.id}>{c.name} · {c.start_date}</option>)}</select></label><p>{slot?.cycle?.scheduled_at?new Date(slot.cycle.scheduled_at).toLocaleString("ko-KR",{timeZone:"Asia/Seoul"}):"회차 조회 중"} · 시험지 출력 1시간 전 · 대기 입장 5분 전</p><div className="summary"><b>참가 {rows.length}명</b><b>배정 {rows.filter((r:any)=>r.exam_id).length}명</b><b>시작 가능 {eligible.length}명</b><b>SOS 미완료 {assigned.filter((r:any)=>!r.sos_gate_open).length}명</b></div><div className="actions"><button className="secondary-button" disabled={!slot||busy||started||!assigned.length} onClick={()=>void act("prepare")}>① 회차 타이머 생성</button><button className="primary-button" disabled={!slot||busy||started||!prepared} onClick={()=>void act("start")}>{started?"시작된 회차":"② 회차 전체 시험 시작"}</button>{started&&!paused?<button className="secondary-button" disabled={busy} onClick={()=>void act("pause")}>회차 전체 일시정지</button>:null}{paused?<button className="primary-button" disabled={busy} onClick={()=>void act("resume")}>회차 전체 재개</button>:null}</div><p role="status">{busy?"처리 중…":message}</p>{assigned.some((r:any)=>!r.sos_gate_open)?<p>SOS 미완료: {assigned.filter((r:any)=>!r.sos_gate_open).map((r:any)=>r.students?.name).join(", ")}</p>:null}<small>아래 시험지는 시작 대상 선택이 아닌, 이 회차의 학생별 답안·제출 현황 조회용입니다.</small><style jsx>{`.cycle-start{padding:24px;border:1px solid #dce5df;border-radius:16px;background:white;margin-bottom:20px}.cycle-start h2{margin:6px 0}.cycle-start p{color:#66756c}.cycle-start small{color:#386b4a}.cycle-start label{display:grid;gap:8px;font-weight:800}.cycle-start select{padding:12px;border:1px solid #cddbd1;border-radius:9px;width:100%;max-width:600px}.summary,.actions{display:flex;gap:12px;flex-wrap:wrap;margin:16px 0}.summary b{background:#f1f6f2;border-radius:8px;padding:10px}.actions button:disabled{opacity:.5;cursor:not-allowed}`}</style></section>;
}
