"use client";
import {useEffect,useState} from "react";
export default function ScheduleStart(){
 const [cycles,setCycles]=useState<any[]>([]),[id,setId]=useState(""),[slot,setSlot]=useState<any>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
 useEffect(()=>{fetch("/api/admin/learning-cycles",{cache:"no-store"}).then(r=>r.json()).then(j=>setCycles(j.cycles??[])).catch(()=>setError("일정 조회 실패"));},[]);
 useEffect(()=>{if(!id){setSlot(null);return;}let active=true;const load=()=>fetch(`/api/admin/exam-slots?cycleId=${id}`,{cache:"no-store"}).then(async r=>{const j=await r.json();if(!r.ok)throw Error(j.message);if(active)setSlot(j);}).catch(e=>{if(active)setError(e.message);});void load();const t=setInterval(load,10000);return()=>{active=false;clearInterval(t);};},[id]);
 const running=slot?.rows?.some((r:any)=>r.booking_status==="IN_PROGRESS");
 const act=async(action:string)=>{if(action==="start"&&!confirm("선택한 일정의 배정 학생들에게 시험을 시작할까요?"))return;setBusy(true);try{const r=await fetch("/api/admin/exam-slots",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({action,cycleId:id})});const j=await r.json();if(!r.ok)throw Error(j.message);setError(action==="prepare"?"타이머 준비 완료":"시험을 시작했습니다.");const next=await fetch(`/api/admin/exam-slots?cycleId=${id}`,{cache:"no-store"});setSlot(await next.json());}catch(e){setError(e instanceof Error?e.message:"처리 실패");}finally{setBusy(false);}};
 return <section style={{background:"white",padding:24,border:"1px solid #dce5df",borderRadius:16,marginBottom:24}}><h2>일정별 전체 시험 시작</h2><p>배정한 학생별 시험지를 같은 시간에 시작합니다. 학생은 대기 화면에서 동의 후 응시합니다.</p><select aria-label="진행할 참가 일정" value={id} onChange={e=>{setId(e.target.value);setSlot(null);setError("");}} style={{padding:12,minWidth:300}}><option value="">참가 일정을 선택하세요</option>{cycles.map(c=><option key={c.id} value={c.id}>{c.name} · {c.start_date}</option>)}</select><p>{slot?`참가 ${slot.rows.length}명 · 시험지 배정 ${slot.rows.filter((r:any)=>r.exam_id).length}명 · SOS 보류 ${slot.rows.filter((r:any)=>!r.sos_gate_open).length}명`:""}</p><button disabled={!slot||busy||running} onClick={()=>void act("prepare")} className="secondary-button">타이머 생성</button>{" "}<button disabled={!slot||busy||running} onClick={()=>void act("start")} className="primary-button" style={{fontSize:22,padding:"18px 40px"}}>{running?"시험 진행 중":"전체 시험 시작"}</button><p role="status">{error}</p><small>아래에서는 시험지별 답안·제출 현황과 일시정지·재개를 관리합니다.</small></section>;
}
