"use client";
import { useCallback, useEffect, useState } from "react";
import { isArchivedPracticeExam } from "@/lib/archived-practice-exams";
const scopes=[{code:"ALGEBRA",letter:"A",label:"대수"},{code:"ALGEBRA_CALC1",letter:"B",label:"대수+미적1"},{code:"FULL",letter:"C",label:"대수+미적1+확통"}];
const title=(n:number,s:string)=>`SOS_${scopes.find(x=>x.code===s)?.letter??"C"}_실전모의고사_${n}`;
export default function WeeklyAssignments({mode="assign"}:{mode?:"assign"|"catalog"}){
  const [data,setData]=useState<any>({cycles:[],catalog:[],exams:[],rows:[]});
  const [cycle,setCycle]=useState(""),[error,setError]=useState(""),[busy,setBusy]=useState(""),[loading,setLoading]=useState(true);
  const [sequence,setSequence]=useState(1),[choices,setChoices]=useState<Record<string,string>>({}),[drafts,setDrafts]=useState<Record<string,{n:number;s:string}>>({});
  const load=useCallback(async()=>{
    setLoading(true);
    try{const r=await fetch(`/api/admin/exam-catalog${cycle?`?cycleId=${encodeURIComponent(cycle)}`:""}`,{cache:"no-store"});const j=await r.json();if(!r.ok)throw new Error(j.message);setData(j);if(mode==="assign"&&!cycle&&j.cycles.length){const today=new Date().toISOString().slice(0,10);setCycle((j.cycles.filter((c:any)=>c.start_date>=today).sort((a:any,b:any)=>a.start_date.localeCompare(b.start_date))[0]??j.cycles[0]).id);}setError("");setDrafts({});}catch(e){setError(e instanceof Error?e.message:"조회 실패");}finally{setLoading(false);}
  },[cycle,mode]);
  useEffect(()=>{void load();},[load]);
  async function save(key:string,body:any){setBusy(key);setError("");try{const r=await fetch("/api/admin/exam-catalog",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(body)});const j=await r.json();if(!r.ok)throw new Error(j.message);await load();}catch(e){setError(e instanceof Error?e.message:"저장 실패");}finally{setBusy("");}}
  const selected=data.cycles.find((c:any)=>c.id===cycle);
  return <section className="weekly">
    <header><div><h2>{mode==="assign"?"회차별 시험배정":"A/B/C 시험지 등록"}</h2><p>{mode==="catalog"?"A/B/C 범위별로 공식 시험순번에 사용할 시험지를 등록합니다.":"선택한 운영 주차의 등록 학생에게 시험순번과 범위에 맞는 시험지를 배정합니다."}</p></div><span className="time">수요일 밤 11시 · 100분</span></header>
    {error&&<p role="alert" className="error">{error}</p>}
    {mode==="catalog"?<>
      <div className="toolbar"><label>공식 시험순번<input type="number" min={1} value={sequence} onChange={e=>{setSequence(Math.max(1,Number(e.target.value)||1));setChoices({});}}/></label><a href="/admin?menu=exam-input">＋ 새 시험지 파일 등록</a></div>
      <p>먼저 시험지 입력에서 파일·정답을 저장한 뒤, 아래 A/B/C에 해당 시험지를 연결하세요.</p>
      <div className="catalog">{scopes.map(scope=>{const entry=data.catalog.find((c:any)=>c.formal_sequence===sequence&&c.scope_code===scope.code);const exam=data.exams.find((e:any)=>e.id===entry?.exam_id);const value=choices[scope.code]??entry?.exam_id??"";return <article key={scope.code}><div className="scope">{scope.letter}</div><h3>{scope.label}</h3><strong>{title(sequence,scope.code)}</strong><label>등록된 시험지 선택<select value={value} onChange={e=>setChoices({...choices,[scope.code]:e.target.value})}><option value="">시험지를 선택하세요</option>{data.exams.filter((e:any)=>!isArchivedPracticeExam(e)).map((e:any)=><option key={e.id} value={e.id}>{e.title} · {e.exam_date}</option>)}</select></label><p>{exam?`연결됨: ${exam.title}`:"아직 등록된 시험지가 없습니다."}</p><small>{exam?`시험지 PDF ${exam.test_file_path?"있음":"없음"} · 해설 PDF ${exam.solution_file_path?"있음":"없음"} · ${exam.question_count}문항`:""}</small><button disabled={!!busy||!value} onClick={()=>void save(scope.code,{action:"catalog",formalSequence:sequence,scopeCode:scope.code,examId:value})}>{busy===scope.code?"저장 중…":"시험지 연결 저장"}</button></article>})}</div>
      <h3>등록된 전체 시험순번</h3><div className="catalog-list">{Array.from(new Set<number>(data.catalog.map((c:any)=>Number(c.formal_sequence)))).sort((a,b)=>a-b).map(n=><button key={n} onClick={()=>{setSequence(n);setChoices({});}}><b>{n}회 시험지</b>{scopes.map(s=><span key={s.code}>{s.letter} {data.catalog.some((c:any)=>c.formal_sequence===n&&c.scope_code===s.code)?"등록 완료":"미등록"}</span>)}</button>)}</div>
    </>:<>
      <div className="toolbar"><label>운영 주차 · 참가일<select value={cycle} onChange={e=>setCycle(e.target.value)}>{data.cycles.map((c:any)=><option key={c.id} value={c.id}>{c.name} · {c.start_date}</option>)}</select></label><button className="secondary" disabled={!!busy||loading} onClick={()=>void load()}>새로고침</button></div>
      <div className="summary"><div><small>선택한 참가 일정</small><b>{selected?.name??"일정 없음"}</b><span>{selected?.start_date} · 밤 11시</span></div><div><small>등록 학생</small><b>{data.rows.length}명</b></div><div><small>배정 완료</small><b>{data.rows.filter((r:any)=>r.registration).length}명</b></div><div><small>미배정</small><b>{data.rows.filter((r:any)=>!r.registration).length}명</b></div></div>
      <div className="table-wrap"><table><thead><tr><th>학생 / 학교·학년</th><th>공식 응시 이력</th><th>이번 시험순번·범위</th><th>배정 시험지</th><th>SOS 상태</th><th>배정</th></tr></thead><tbody>{data.rows.map((row:any)=>{const d=drafts[row.id]??{n:row.registration?.formal_sequence??row.next_sequence,s:row.scope_code??"FULL"};const entry=data.catalog.find((c:any)=>c.formal_sequence===d.n&&c.scope_code===d.s);const target=data.exams.find((e:any)=>e.id===entry?.exam_id);const student=Array.isArray(row.students)?row.students[0]:row.students;return <tr key={row.id}><td><b>{student?.name}</b><small>{student?.school} · {student?.grade}</small></td><td><b>{row.completed_sequence?`${row.completed_sequence}회 완료`:"첫 응시"}</b><small>다음 시험 {row.next_sequence}회</small></td><td><div className="selection"><input aria-label={`${student?.name} 시험순번`} type="number" min={1} value={d.n} disabled={row.locked||!!busy} onChange={e=>setDrafts({...drafts,[row.id]:{...d,n:Math.max(1,Number(e.target.value)||1)}})}/><select aria-label={`${student?.name} 시험범위`} value={d.s} disabled={row.locked||!!busy} onChange={e=>setDrafts({...drafts,[row.id]:{...d,s:e.target.value}})}>{scopes.map(s=><option key={s.code} value={s.code}>{s.letter} · {s.label}</option>)}</select></div></td><td><b>{row.registration?title(row.registration.formal_sequence,row.registration.scope_code):"미배정"}</b><small>{row.exam?.title??"시험지 배정 후 학생 일정에 표시됩니다."}</small><small className={target?"":"warning"}>선택: {target?.title??"해당 시험지 미등록"}</small></td><td><span className={row.sos_passed?"badge":"badge warning"}>{row.sos_passed?row.completed_sequence?"통과 확인":"첫 응시 · 가능":"이전 SOS 통과 대기"}</span></td><td><button disabled={!!busy||row.locked||!entry} onClick={()=>void save(row.id,{action:"assign",membershipId:row.id,formalSequence:d.n,scopeCode:d.s})}>{busy===row.id?"저장 중…":row.locked?"응시 시작됨":row.registration?"배정 변경":"시험지 배정"}</button></td></tr>})}</tbody></table></div>
      {!data.rows.length&&<p className="empty">{loading?"등록 학생을 불러오는 중입니다…":"이 주차에 등록된 학생이 없습니다. 참가권 신청·결제에서 등록을 완료해 주세요."}</p>}
    </>}
    <style jsx>{`
      .weekly{color:#24382b}.weekly header,.toolbar{display:flex;justify-content:space-between;align-items:center;gap:20px;margin-bottom:22px}.weekly h2{font-size:26px;margin:0 0 8px}.weekly p,.weekly small{color:#718077;font-size:13px}.time,.badge{padding:9px 12px;background:#edf5ef;border-radius:8px;font-size:12px;white-space:nowrap}nav{display:flex;gap:8px;border-bottom:1px solid #dce5df;margin:20px 0 24px;padding-bottom:12px}button,a{border:0;border-radius:9px;padding:12px 16px;background:#245735;color:white;font-weight:700;cursor:pointer;text-decoration:none}nav button,.secondary{background:white;color:#48614f;border:1px solid #dce5df}nav .on{background:#245735;color:white}button:disabled{opacity:.45;cursor:default}label{display:grid;gap:8px;font-weight:700;font-size:13px}select,input{width:100%;min-width:0;box-sizing:border-box;background:white;color:#24382b;border:1px solid #d5dfd8;border-radius:8px;padding:10px;font:inherit}input[type=number]{width:85px}.toolbar label{min-width:280px}.catalog{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:18px;margin:20px 0 30px}.catalog article{padding:24px;background:white;border:1px solid #dce5df;border-radius:16px;display:flex;flex-direction:column;gap:15px}.catalog h3,.catalog p{margin:0}.catalog strong{font-size:14px;overflow-wrap:anywhere}.scope{background:#eaf3ed;color:#245735;border-radius:10px;width:48px;height:48px;display:grid;place-items:center;font-size:26px;font-weight:800}.catalog button{margin-top:auto}.catalog-list{display:grid;gap:8px}.catalog-list button{display:flex;gap:30px;background:white;color:#245735;border:1px solid #dce5df}.summary{display:flex;gap:45px;background:white;border:1px solid #dce5df;padding:22px;border-radius:13px;margin:20px 0}.summary div{display:grid;gap:7px}.summary span{font-size:13px;color:#718077}.table-wrap{overflow:auto;background:white;border:1px solid #dce5df;border-radius:14px}table{border-collapse:collapse;width:100%;min-width:1050px;text-align:left;font-size:13px}th{background:#f0f5f1;padding:16px;color:#65776a}td{padding:20px 16px;border-top:1px solid #edf0ee}td small{display:block;margin-top:7px}td b{display:block}.selection{display:flex;gap:7px}.selection select{width:185px}.selection input{width:65px}.warning{color:#a76724!important;background:#fff5e8}.error{background:#fff0ee;color:#a13c31!important;padding:15px;border-radius:9px}.empty{text-align:center;padding:45px}@media(max-width:850px){.catalog{grid-template-columns:1fr}.weekly header,.toolbar{align-items:stretch;flex-direction:column}.summary{gap:20px;flex-wrap:wrap}}
    `}</style>
  </section>;
}
