"use client";
import { useEffect, useState, type FormEvent } from "react";

const money = (v: number) => new Intl.NumberFormat("ko-KR").format(v ?? 0);
const date = (v: string) => v ? new Date(`${v}T00:00:00`).toLocaleDateString("ko-KR", { month: "long", day: "numeric", weekday: "short" }) : "-";

export default function ProgramApplyPage() {
  const [batches, setBatches] = useState<any[]>([]), [selected, setSelected] = useState("");
  const [form, setForm] = useState({ parentName: "", parentPhone: "", studentName: "", studentPhone: "", school: "", grade: "고1" });
  const [loading, setLoading] = useState(true), [busy, setBusy] = useState(false), [message, setMessage] = useState("");
  useEffect(() => { void (async () => { try { const r = await fetch("/api/program-applications", { cache: "no-store" }); const j = await r.json(); if (!r.ok) throw new Error(j.message); setBatches(j.batches ?? []); setSelected(String(j.batches?.[0]?.id ?? "")); } catch (e) { setMessage(e instanceof Error ? e.message : "모집 정보를 불러오지 못했습니다."); } finally { setLoading(false); } })(); }, []);
  const submit = async (e: FormEvent) => { e.preventDefault(); if (!selected || busy) return; setBusy(true); setMessage(""); try { const r = await fetch("/api/program-applications", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ batchId: selected, ...form }) }); const j = await r.json(); if (!r.ok) throw new Error(j.message); setMessage("신청이 접수되었습니다. 입금 확인 후 학생·학부모 계정과 5개 회차가 연결됩니다."); } catch (e) { setMessage(e instanceof Error ? e.message : "신청하지 못했습니다."); } finally { setBusy(false); } };
  const batch = batches.find((x) => String(x.id) === selected);
  return <main className="apply-page">
    <header><a href="/"><img src="/mathpooh-logo.png" alt="" /><b>MATHPOOH SOS</b></a><a href="/parent-login">학부모 로그인</a></header>
    <section className="intro"><small>5-WEEK PERSONALIZED PROGRAM</small><h1>SOS 5회 프로그램 신청</h1><p>실전모의고사 5회와 시험 결과에 따른 개인별 SOS 학습을 한 묶음으로 신청합니다.</p></section>
    {loading ? <div className="state">신청 가능한 일정을 불러오고 있습니다.</div> : !batches.length ? <div className="state">현재 신청 가능한 5회 프로그램이 없습니다.</div> : <form onSubmit={submit}>
      <section className="batch-list"><h2>① 5회 일정 확인</h2>{batches.map((b) => <button type="button" key={b.id} className={selected === String(b.id) ? "on" : ""} onClick={() => setSelected(String(b.id))}><span><b>{b.title}</b><small>실전모의고사 + 개인별 SOS 학습 · 총 5회</small></span><strong>{money(b.price)}원</strong></button>)}</section>
      {batch ? <section className="schedule"><h3>{batch.title} 일정</h3><div>{batch.cycles.map((c: any) => <article key={c.id}><b>{c.slot_no}회차</b><span>{date(c.start_date)}</span><small>{c.name}</small></article>)}</div></section> : null}
      <section className="fields"><h2>② 신청 정보 입력</h2><div><label>학부모 성함<input required value={form.parentName} onChange={e => setForm({ ...form, parentName: e.target.value })} /></label><label>학부모 전화번호<input required inputMode="numeric" placeholder="01012345678" value={form.parentPhone} onChange={e => setForm({ ...form, parentPhone: e.target.value })} /></label><label>학생 이름<input required value={form.studentName} onChange={e => setForm({ ...form, studentName: e.target.value })} /></label><label>학생 전화번호<input inputMode="numeric" placeholder="계정 생성에 사용" value={form.studentPhone} onChange={e => setForm({ ...form, studentPhone: e.target.value })} /></label><label>학교<input required value={form.school} onChange={e => setForm({ ...form, school: e.target.value })} /></label><label>학년<select value={form.grade} onChange={e => setForm({ ...form, grade: e.target.value })}><option>고1</option><option>고2</option><option>고3</option><option>중3</option></select></label></div></section>
      <label className="agree"><input required type="checkbox" /> 신청 및 계정 연결을 위해 입력한 정보를 사용하는 데 동의합니다.</label>
      <button className="submit" disabled={busy}>{busy ? "신청 접수 중…" : `${batch?.title ?? "SOS 5회"} 신청하기`}</button>
      {message ? <p className="message">{message}</p> : null}
    </form>}
    <style jsx>{`
      :global(body){margin:0;background:#f3f7f4;color:#17251b;font-family:Arial,"Noto Sans KR",sans-serif}.apply-page{min-height:100vh}.apply-page>header{height:72px;padding:0 max(24px,calc((100vw - 1040px)/2));display:flex;align-items:center;justify-content:space-between;background:#fff;border-bottom:1px solid #dbe5dd}.apply-page>header a{display:flex;align-items:center;gap:9px;color:#285c31;text-decoration:none;font-weight:900}.apply-page>header img{width:37px}.intro{padding:58px 24px 40px;text-align:center;background:linear-gradient(135deg,#214f2b,#397a45);color:#fff}.intro small{font-weight:900;letter-spacing:.16em}.intro h1{margin:10px 0;font-size:38px}.intro p{margin:0;opacity:.84}.state,form{max-width:920px;margin:30px auto;padding:28px;background:#fff;border:1px solid #dbe5dd;border-radius:20px}form{display:grid;gap:20px}h2,h3{margin:0 0 14px}.batch-list>button{width:100%;display:flex;justify-content:space-between;align-items:center;padding:18px;border:2px solid #e1e8e3;border-radius:14px;background:#fff;text-align:left;cursor:pointer}.batch-list>button.on{border-color:#2f6937;background:#f2f8f3}.batch-list span,.batch-list small{display:block}.batch-list small{margin-top:5px;color:#718077}.batch-list strong{color:#2f6937;font-size:20px}.schedule{padding:20px;background:#f7faf8;border-radius:14px}.schedule>div{display:grid;grid-template-columns:repeat(5,1fr);gap:8px}.schedule article{padding:12px;background:#fff;border:1px solid #dfe7e1;border-radius:10px}.schedule article>*{display:block}.schedule article b{color:#2f6937}.schedule article span{margin:6px 0;font-size:13px;font-weight:800}.schedule article small{color:#768078}.fields>div{display:grid;grid-template-columns:1fr 1fr;gap:13px}.fields label{display:grid;gap:7px;font-size:13px;font-weight:800}.fields input,.fields select{height:46px;border:1px solid #d5dfd7;border-radius:10px;padding:0 12px;background:#fff}.agree{font-size:13px;color:#657269}.submit{height:56px;border:0;border-radius:12px;background:#2f6937;color:#fff;font-size:17px;font-weight:900;cursor:pointer}.submit:disabled{opacity:.55}.message{margin:0;padding:14px;border-radius:10px;background:#eef7ef;color:#285c31;font-weight:800}@media(max-width:700px){.intro h1{font-size:29px}form{margin:18px 12px;padding:19px}.schedule>div{grid-template-columns:1fr}.fields>div{grid-template-columns:1fr}.batch-list>button{align-items:flex-start;gap:10px}.batch-list strong{font-size:16px}}
    `}</style>
  </main>;
}
